# Generated by Django 5.0.6 on 2024-05-29 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nombre', models.CharField(help_text='cliente1', max_length=30)),
                ('telefono', models.CharField(max_length=15)),
                ('tipo_cliente', models.CharField(max_length=30)),
                ('razon_social', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('direccion', models.CharField(max_length=30)),
                ('cliente_mayorista', models.BooleanField(default=False)),
                ('codPostal', models.IntegerField(verbose_name='Codigo Postal')),
                ('email', models.EmailField(max_length=254)),
                ('instagram', models.URLField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destilado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('edicionlimitada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insumo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidoproveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cont_neto', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('insumos_venta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlstock.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Distribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField()),
                ('descripcion', models.CharField(max_length=30)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlstock.cliente')),
                ('id_pedido_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlstock.pedidocliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_insumos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlstock.insumo')),
                ('id_pedidoproveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlstock.pedidoproveedor')),
            ],
        ),
        migrations.AddField(
            model_name='insumo',
            name='id_pedidoproveedor',
            field=models.ManyToManyField(through='controlstock.Pedido_insumo', to='controlstock.pedidoproveedor'),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=50)),
                ('precio_minorista', models.IntegerField()),
                ('precio_mayorista', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('reutilizable', models.BooleanField()),
                ('destilado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlstock.destilado')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoCliente_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedidocliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlstock.pedidocliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlstock.producto')),
            ],
        ),
        migrations.AddField(
            model_name='pedidocliente',
            name='id_producto',
            field=models.ManyToManyField(through='controlstock.PedidoCliente_Producto', to='controlstock.producto'),
        ),
        migrations.CreateModel(
            name='distribucion_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlstock.distribucion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlstock.producto')),
            ],
        ),
        migrations.AddField(
            model_name='pedidoproveedor',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlstock.proveedor'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlstock.proveedor'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlstock.provincia'),
        ),
    ]
