# Generated by Django 5.0.6 on 2024-06-05 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlstock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField(choices=[('C', 'Consumidor Final'), ('R', 'Responsable Inscripto'), ('M', 'Monotributista')], default='C', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='distribucion_producto',
            name='distribucion',
        ),
        migrations.RemoveField(
            model_name='distribucion_producto',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_cliente',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='id_pedidoproveedor',
        ),
        migrations.AddField(
            model_name='insumo',
            name='contenido_neto',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='insumo',
            name='fecha_de_vencimiento',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidoproveedor',
            name='producto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='controlstock.producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(help_text='Introduce direccion de tu punto de venta', max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Distribucion',
        ),
        migrations.DeleteModel(
            name='distribucion_producto',
        ),
    ]
