# Generated by Django 5.0.6 on 2024-06-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlstock', '0002_tipocliente_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tipoCliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('C', 'Consumidor Final'), ('R', 'Responsable Inscripto'), ('M', 'Monotributista')], default='C', max_length=1),
        ),
    ]
