# Generated by Django 5.0.6 on 2024-06-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlstock', '0003_delete_tipocliente_cliente_tipo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='punto_venta',
            field=models.BooleanField(default=False),
        ),
    ]
