# Generated by Django 5.0.6 on 2024-06-05 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlstock', '0004_cliente_punto_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidocliente',
            name='id_producto',
        ),
        migrations.AddField(
            model_name='pedidocliente',
            name='id_producto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='controlstock.producto'),
            preserve_default=False,
        ),
    ]
