# Generated by Django 5.0.6 on 2024-06-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlstock', '0005_remove_pedidocliente_id_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidocliente',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='pedidocliente',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='pedidocliente',
            name='precio',
        ),
        migrations.AddField(
            model_name='pedidocliente_producto',
            name='cantidad',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
