# Generated by Django 5.0.6 on 2024-06-08 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlstock', '0006_remove_pedidocliente_cantidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidocliente_producto',
            old_name='pedidocliente',
            new_name='id_pedidocliente',
        ),
        migrations.RenameField(
            model_name='pedidocliente_producto',
            old_name='producto',
            new_name='id_producto',
        ),
        migrations.RemoveField(
            model_name='pedidoproveedor',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='pedidoproveedor',
            name='cont_neto',
        ),
        migrations.RemoveField(
            model_name='pedidoproveedor',
            name='producto',
        ),
        migrations.CreateModel(
            name='PedidoProveedor_Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('id_insumos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlstock.insumo')),
                ('id_pedidoproveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlstock.pedidoproveedor')),
            ],
        ),
        migrations.DeleteModel(
            name='Pedido_insumo',
        ),
    ]
