# Generated by Django 5.0.6 on 2024-06-08 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlstock', '0007_rename_pedidocliente_pedidocliente_producto_id_pedidocliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidoproveedor',
            old_name='precio',
            new_name='total',
        ),
    ]
