# Generated by Django 5.1 on 2024-09-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlstock', '0008_rename_precio_pedidoproveedor_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
    ]
