# Generated by Django 5.1 on 2024-09-02 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlstock', '0009_alter_producto_descripcion_alter_proveedor_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='destilado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='controlstock.destilado'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_mayorista',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_minorista',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
