# Generated by Django 4.1.2 on 2024-10-08 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlstock', '0010_alter_producto_destilado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_proveedor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='controlstock.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Compra_Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('id_compra', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='controlstock.compra')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlstock.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Venta_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pedidocliente_producto',
            name='id_pedidocliente',
        ),
        migrations.RemoveField(
            model_name='pedidocliente_producto',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='pedidoproveedor',
            name='id_proveedor',
        ),
        migrations.RemoveField(
            model_name='pedidoproveedor_insumo',
            name='id_insumos',
        ),
        migrations.RemoveField(
            model_name='pedidoproveedor_insumo',
            name='id_pedidoproveedor',
        ),
        migrations.AlterField(
            model_name='insumo',
            name='fecha_de_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='id_proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='controlstock.proveedor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='PedidoCliente',
        ),
        migrations.DeleteModel(
            name='PedidoCliente_Producto',
        ),
        migrations.DeleteModel(
            name='Pedidoproveedor',
        ),
        migrations.DeleteModel(
            name='PedidoProveedor_Insumo',
        ),
        migrations.AddField(
            model_name='venta_producto',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlstock.producto'),
        ),
        migrations.AddField(
            model_name='venta_producto',
            name='id_venta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='controlstock.venta'),
        ),
        migrations.AddField(
            model_name='compra_insumo',
            name='id_insumo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='controlstock.insumo'),
        ),
    ]
