# Generated by Django 4.1.2 on 2024-10-08 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlstock', '0011_compra_compra_insumo_venta_venta_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compra',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlstock.proveedor'),
        ),
        migrations.AlterField(
            model_name='compra_insumo',
            name='id_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlstock.compra'),
        ),
        migrations.AlterField(
            model_name='compra_insumo',
            name='id_insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlstock.insumo'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlstock.proveedor'),
        ),
        migrations.AlterField(
            model_name='venta_producto',
            name='id_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlstock.venta'),
        ),
    ]
