# Generated by Django 4.1.2 on 2024-10-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlstock', '0012_venta_anulado_alter_compra_id_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
