# Generated by Django 5.1.3 on 2025-02-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlstock', '0013_compra_anulado_alter_compra_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
