# Generated by Django 5.1.6 on 2025-02-20 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlstock', '0014_producto_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio_mayorista',
            new_name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_minorista',
        ),
    ]
