# Generated by Django 5.1.6 on 2025-03-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlstock', '0016_alter_cliente_direccion_alter_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta_producto',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta_producto',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
