# Generated by Django 5.1.6 on 2025-03-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlstock', '0016_alter_cliente_direccion_alter_cliente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='contenido_neto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
