# Generated by Django 5.1.6 on 2025-03-15 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlstock', '0017_alter_insumo_contenido_neto'),
        ('controlstock', '0017_venta_producto_precio_unitario_and_more'),
    ]

    operations = [
    ]
