# Generated by Django 5.1.3 on 2025-03-17 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlstock', '0018_merge_20250315_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='insumos_venta',
        ),
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insumos', to='controlstock.proveedor'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='insumo',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
