# Generated by Django 5.1.6 on 2025-03-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlstock', '0019_remove_proveedor_insumos_venta_alter_compra_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra_insumo',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='compra_insumo',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
