# Generated by Django 5.1.6 on 2025-03-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlstock', '0020_compra_insumo_precio_unitario_compra_insumo_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
