# Generated by Django 5.1.3 on 2025-03-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlstock', '0021_venta_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='unidad_medida',
            field=models.CharField(blank=True, choices=[('L', 'Litros'), ('ML', 'Mililitros'), ('KG', 'Kilogramos'), ('G', 'Gramos'), ('UN', 'Unidades'), ('M', 'Metros'), ('CM', 'Centímetros'), ('', 'Sin especificar')], default='', max_length=5, null=True),
        ),
    ]
