# Generated by Django 5.1.3 on 2025-03-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlstock', '0022_insumo_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='unidad_medida',
            field=models.CharField(blank=True, choices=[('L', 'Litros'), ('ML', 'Mililitros'), ('KG', 'Kilogramos'), ('G', 'Gramos'), ('UN', 'Unidades'), ('', 'Sin especificar')], default='', max_length=5, null=True),
        ),
    ]
