# Generated by Django 5.1.3 on 2025-03-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlstock', '0023_alter_insumo_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='unidad_medida',
            field=models.CharField(blank=True, choices=[('Lts', 'Litros'), ('Ml', 'Mililitros'), ('Kg', 'Kilogramos'), ('Gr', 'Gramos'), ('Un', 'Unidades'), ('', 'Sin especificar')], default='', max_length=5, null=True),
        ),
    ]
